[package]
name = "las_voxelizer"
version = "0.1.0"
edition = "2024"

[lib]
name = "las_voxelizer"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png", "tiff"] }
las = { version = "0.9.10", features = ["laz-parallel"] }
rayon = "1"
rustc-hash = "2"
