// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution(arg1) {
  return window['go']['main']['App']['CancelExecution'](arg1);
}

export function DeleteSSHConnection(arg1) {
  return window['go']['main']['App']['DeleteSSHConnection'](arg1);
}

export function GetWorkbenchBootstrap() {
  return window['go']['main']['App']['GetWorkbenchBootstrap']();
}

export function ListSSHConnections() {
  return window['go']['main']['App']['ListSSHConnections']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenSaveFileDialog(arg1) {
  return window['go']['main']['App']['OpenSaveFileDialog'](arg1);
}

export function SaveSSHConnection(arg1) {
  return window['go']['main']['App']['SaveSSHConnection'](arg1);
}

export function StartLocalExecution(arg1) {
  return window['go']['main']['App']['StartLocalExecution'](arg1);
}

export function StartRemoteExecution(arg1) {
  return window['go']['main']['App']['StartRemoteExecution'](arg1);
}
