// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ssh} from '../models';

export function CancelActiveGoToolchainTask():Promise<void>;

export function CancelActivePythonToolchainTask():Promise<void>;

export function CancelExecution(arg1:string):Promise<void>;

export function CheckGoToolchainEnvironment():Promise<main.GoToolchainState>;

export function CheckPythonToolchainEnvironment():Promise<main.PythonToolchainState>;

export function ClearArtifactBatchTasks():Promise<void>;

export function DeleteGoToolchainEnvironment():Promise<main.GoToolchainState>;

export function DeletePythonToolchainEnvironment():Promise<main.PythonToolchainState>;

export function DeleteSSHConnection(arg1:string):Promise<void>;

export function DownloadTaskResult(arg1:string):Promise<string>;

export function EstimateArtifactBatchCache(arg1:main.ArtifactBatchRequest):Promise<main.ArtifactBatchEstimate>;

export function ExportTool(arg1:main.ExportToolRequest):Promise<main.ExportToolResult>;

export function GetCurrentWindowState():Promise<main.WindowState>;

export function GetGoToolchainState():Promise<main.GoToolchainState>;

export function GetGoToolchainTaskState():Promise<main.GoToolchainTaskState>;

export function GetPythonToolchainState():Promise<main.PythonToolchainState>;

export function GetPythonToolchainTaskState():Promise<main.PythonToolchainTaskState>;

export function GetSSHConnection(arg1:string):Promise<ssh.Connection>;

export function GetWindowConfig():Promise<main.WindowState>;

export function GetWorkbenchBootstrap():Promise<main.WorkbenchBootstrap>;

export function InstallGoToolchain(arg1:main.InstallGoToolchainRequest):Promise<main.GoToolchainState>;

export function InstallPythonDependencies():Promise<main.PythonToolchainState>;

export function IsWindowRectVisible(arg1:number,arg2:number,arg3:number,arg4:number):Promise<boolean>;

export function ListArtifactBatchTasks():Promise<Array<main.ArtifactBatchTask>>;

export function ListDownloadTasks():Promise<Array<main.DownloadTask>>;

export function ListOfficialGoReleases():Promise<Array<main.GoOfficialRelease>>;

export function ListSSHConnections():Promise<Array<ssh.Connection>>;

export function ListTasks():Promise<Array<main.ExecutionTask>>;

export function OpenFileDialog(arg1:main.FileDialogRequest):Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSaveFileDialog(arg1:main.FileDialogRequest):Promise<string>;

export function PersistCurrentWindowState():Promise<void>;

export function PreparePythonToolchainEnvironment():Promise<main.PythonToolchainState>;

export function SaveGoToolchainConfig(arg1:main.GoToolchainConfig):Promise<main.GoToolchainState>;

export function SavePythonToolchainConfig(arg1:main.PythonToolchainConfig):Promise<main.PythonToolchainState>;

export function SaveSSHConnection(arg1:ssh.Connection):Promise<ssh.Connection>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SaveWindowState(arg1:main.WindowState):Promise<void>;

export function StartArtifactBatch(arg1:main.ArtifactBatchRequest):Promise<main.ArtifactBatchTask>;

export function StartInstallGoToolchain(arg1:main.InstallGoToolchainRequest):Promise<main.GoToolchainTaskState>;

export function StartInstallPythonDependencies():Promise<main.PythonToolchainTaskState>;

export function StartLocalExecution(arg1:main.ExecutionRequest):Promise<main.ExecutionTask>;

export function StartPreparePythonToolchainEnvironment():Promise<main.PythonToolchainTaskState>;

export function StartRemoteExecution(arg1:main.RemoteExecRequest):Promise<main.ExecutionTask>;

export function StartTaskResultDownload(arg1:string):Promise<main.DownloadTask>;

export function TestSSHConnection(arg1:string):Promise<ssh.TestResult>;

export function TestSSHConnectionRaw(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<ssh.TestResult>;

export function UpdateSSHConnection(arg1:string,arg2:ssh.Connection):Promise<void>;
