// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ssh} from '../models';

export function CancelExecution(arg1:string):Promise<void>;

export function DeleteSSHConnection(arg1:string):Promise<void>;

export function ExportTool(arg1:main.ExportToolRequest):Promise<main.ExportToolResult>;

export function GetCurrentWindowState():Promise<main.WindowState>;

export function GetSSHConnection(arg1:string):Promise<ssh.Connection>;

export function GetWindowConfig():Promise<main.WindowState>;

export function GetWorkbenchBootstrap():Promise<main.WorkbenchBootstrap>;

export function IsWindowRectVisible(arg1:number,arg2:number,arg3:number,arg4:number):Promise<boolean>;

export function ListSSHConnections():Promise<Array<ssh.Connection>>;

export function ListTasks():Promise<Array<main.ExecutionTask>>;

export function OpenFileDialog(arg1:main.FileDialogRequest):Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSaveFileDialog(arg1:main.FileDialogRequest):Promise<string>;

export function PersistCurrentWindowState():Promise<void>;

export function SaveSSHConnection(arg1:ssh.Connection):Promise<ssh.Connection>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SaveWindowState(arg1:main.WindowState):Promise<void>;

export function StartLocalExecution(arg1:main.ExecutionRequest):Promise<main.ExecutionTask>;

export function StartRemoteExecution(arg1:main.RemoteExecRequest):Promise<main.ExecutionTask>;

export function TestSSHConnection(arg1:string):Promise<ssh.TestResult>;

export function TestSSHConnectionRaw(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<ssh.TestResult>;

export function UpdateSSHConnection(arg1:string,arg2:ssh.Connection):Promise<void>;
