// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssh} from '../models';
import {main} from '../models';

export function CancelExecution(arg1:string):Promise<void>;

export function DeleteSSHConnection(arg1:string):Promise<void>;

export function GetSSHConnection(arg1:string):Promise<ssh.Connection>;

export function GetWorkbenchBootstrap():Promise<main.WorkbenchBootstrap>;

export function ListSSHConnections():Promise<Array<ssh.Connection>>;

export function ListTasks():Promise<Array<main.ExecutionTask>>;

export function OpenFileDialog(arg1:main.FileDialogRequest):Promise<string>;

export function OpenSaveFileDialog(arg1:main.FileDialogRequest):Promise<string>;

export function SaveSSHConnection(arg1:ssh.Connection):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function StartLocalExecution(arg1:main.ExecutionRequest):Promise<main.ExecutionTask>;

export function StartRemoteExecution(arg1:main.RemoteExecRequest):Promise<main.ExecutionTask>;

export function TestSSHConnection(arg1:string):Promise<ssh.TestResult>;

export function TestSSHConnectionRaw(arg1:string,arg2:number,arg3:string,arg4:string):Promise<ssh.TestResult>;

export function UpdateSSHConnection(arg1:string,arg2:ssh.Connection):Promise<void>;
