// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelActiveGoToolchainTask() {
  return window['go']['main']['App']['CancelActiveGoToolchainTask']();
}

export function CancelActivePythonToolchainTask() {
  return window['go']['main']['App']['CancelActivePythonToolchainTask']();
}

export function CancelExecution(arg1) {
  return window['go']['main']['App']['CancelExecution'](arg1);
}

export function CheckGoToolchainEnvironment() {
  return window['go']['main']['App']['CheckGoToolchainEnvironment']();
}

export function CheckPythonToolchainEnvironment() {
  return window['go']['main']['App']['CheckPythonToolchainEnvironment']();
}

export function ClearArtifactBatchTasks() {
  return window['go']['main']['App']['ClearArtifactBatchTasks']();
}

export function DeleteGoToolchainEnvironment() {
  return window['go']['main']['App']['DeleteGoToolchainEnvironment']();
}

export function DeletePythonToolchainEnvironment() {
  return window['go']['main']['App']['DeletePythonToolchainEnvironment']();
}

export function DeleteSSHConnection(arg1) {
  return window['go']['main']['App']['DeleteSSHConnection'](arg1);
}

export function EstimateArtifactBatchCache(arg1) {
  return window['go']['main']['App']['EstimateArtifactBatchCache'](arg1);
}

export function ExportTool(arg1) {
  return window['go']['main']['App']['ExportTool'](arg1);
}

export function GetCurrentWindowState() {
  return window['go']['main']['App']['GetCurrentWindowState']();
}

export function GetGoToolchainState() {
  return window['go']['main']['App']['GetGoToolchainState']();
}

export function GetGoToolchainTaskState() {
  return window['go']['main']['App']['GetGoToolchainTaskState']();
}

export function GetPythonToolchainState() {
  return window['go']['main']['App']['GetPythonToolchainState']();
}

export function GetPythonToolchainTaskState() {
  return window['go']['main']['App']['GetPythonToolchainTaskState']();
}

export function GetSSHConnection(arg1) {
  return window['go']['main']['App']['GetSSHConnection'](arg1);
}

export function GetWindowConfig() {
  return window['go']['main']['App']['GetWindowConfig']();
}

export function GetWorkbenchBootstrap() {
  return window['go']['main']['App']['GetWorkbenchBootstrap']();
}

export function InstallGoToolchain(arg1) {
  return window['go']['main']['App']['InstallGoToolchain'](arg1);
}

export function InstallPythonDependencies() {
  return window['go']['main']['App']['InstallPythonDependencies']();
}

export function IsWindowRectVisible(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IsWindowRectVisible'](arg1, arg2, arg3, arg4);
}

export function ListArtifactBatchTasks() {
  return window['go']['main']['App']['ListArtifactBatchTasks']();
}

export function ListOfficialGoReleases() {
  return window['go']['main']['App']['ListOfficialGoReleases']();
}

export function ListSSHConnections() {
  return window['go']['main']['App']['ListSSHConnections']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenSaveFileDialog(arg1) {
  return window['go']['main']['App']['OpenSaveFileDialog'](arg1);
}

export function PersistCurrentWindowState() {
  return window['go']['main']['App']['PersistCurrentWindowState']();
}

export function PreparePythonToolchainEnvironment() {
  return window['go']['main']['App']['PreparePythonToolchainEnvironment']();
}

export function SaveGoToolchainConfig(arg1) {
  return window['go']['main']['App']['SaveGoToolchainConfig'](arg1);
}

export function SavePythonToolchainConfig(arg1) {
  return window['go']['main']['App']['SavePythonToolchainConfig'](arg1);
}

export function SaveSSHConnection(arg1) {
  return window['go']['main']['App']['SaveSSHConnection'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}

export function StartArtifactBatch(arg1) {
  return window['go']['main']['App']['StartArtifactBatch'](arg1);
}

export function StartInstallGoToolchain(arg1) {
  return window['go']['main']['App']['StartInstallGoToolchain'](arg1);
}

export function StartInstallPythonDependencies() {
  return window['go']['main']['App']['StartInstallPythonDependencies']();
}

export function StartLocalExecution(arg1) {
  return window['go']['main']['App']['StartLocalExecution'](arg1);
}

export function StartPreparePythonToolchainEnvironment() {
  return window['go']['main']['App']['StartPreparePythonToolchainEnvironment']();
}

export function StartRemoteExecution(arg1) {
  return window['go']['main']['App']['StartRemoteExecution'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function TestSSHConnectionRaw(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestSSHConnectionRaw'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSSHConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateSSHConnection'](arg1, arg2);
}
