// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelExecution(arg1:string):Promise<void>;

export function GetWorkbenchBootstrap():Promise<main.WorkbenchBootstrap>;

export function ListTasks():Promise<Array<main.ExecutionTask>>;

export function StartLocalExecution(arg1:main.ExecutionRequest):Promise<main.ExecutionTask>;
