// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution(arg1) {
  return window['go']['main']['App']['CancelExecution'](arg1);
}

export function GetWorkbenchBootstrap() {
  return window['go']['main']['App']['GetWorkbenchBootstrap']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function StartLocalExecution(arg1) {
  return window['go']['main']['App']['StartLocalExecution'](arg1);
}
